#$all format minus a couple packages and langs
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$directory\
$vcsh\
$package\
$conda\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$character"""

# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜ ](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜ ](bold red)" 

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = ""
style = "bold white"
format = '[\($symbol$branch\)](bold cyan) '

#[git_status]
# I don't care about untracked files or that there's a stash present.
#untracked = ""
#format = '([\[$conflicted$deleted$renamed$modified$staged$behind\]]($style) )'
#modified = '*'

[status]
disabled = false
format = '[\[$status - $common_meaning\]](green)'

[conda]
format = '[\($environment\)](green) '
ignore_base = false

[username]
format = "[$user]($style) "
show_always = true

[directory]
truncation_length = 10


